# Generated by Django 6.0.2 on 2026-04-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_descripcion_productofoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_categoria',
            field=models.CharField(default='Sin descripción', max_length=150),
        ),
    ]
