# Generated by Django 6.0.2 on 2026-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='slider_img_home/')),
                ('image_alt', models.CharField(blank=True, max_length=150)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(default=True, max_length=30)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
