# Generated by Django 6.0.2 on 2026-03-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide_home',
            name='cta_url',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='slide_home',
            name='subtitle',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='slide_home',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
