# Generated by Django 6.0.2 on 2026-03-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_slide_home_cta_url_alter_slide_home_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide_clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_clientes_home/')),
                ('image_alt', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
