# Generated by Django 6.0.2 on 2026-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='canal',
            field=models.CharField(choices=[('transformador', 'Transformador'), ('marmolero', 'Marmolero'), ('carpintero', 'Carpintero'), ('mueblero', 'Mueblero'), ('cocinista', 'Cocinista'), ('constructora', 'Constructora'), ('distribuidor', 'Distribuidor'), ('inmobiliaria', 'Inmobiliaria'), ('arquitecto', 'Arquitecto'), ('ingeniero', 'Ingeniero'), ('cliente_particular', 'Cliente particular')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefono',
            field=models.IntegerField(max_length=20),
        ),
    ]
