# Generated by Django 6.0.2 on 2026-03-02 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_lead_canal_alter_lead_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Ingresa solo numeros y un '+' opcional al inicio.", regex='^\\+?\\d+$')]),
        ),
    ]
