# Generated by Django 6.0.2 on 2026-03-02

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0003_alter_lead_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="telefono",
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
